using Atomic.Entities;

/**
 * Created by Entity Domain Generator.
 */

namespace SampleGame.Gameplay
{
    /// <summary>
    /// Provides a pooled manager for <see cref="ActorView"/> instances bound to <see cref="IActor"/> entities.
    /// </summary>
    /// <remarks>
    /// This class is auto-generated by <b>Entity Domain Generator</b>.
    /// It inherits from <see cref="EntityViewPool{TEntity, TView}"/> and is specialized for <see cref="Actor"/>.
    /// </remarks>
    public sealed class ActorViewPool : EntityViewPool<IActor, ActorView>
    {
    }
}
