using Atomic.Entities;

/**
 * Created by Entity Domain Generator.
 */

namespace SampleGame.Gameplay
{
    /// <summary>
    /// A collection view responsible for displaying and managing multiple <see cref="ActorView"/> instances bound to <see cref="IActor"/> entities.
    /// </summary>
    /// <remarks>
    /// This class is automatically generated by <b>Entity Domain Generator</b>.
    /// It inherits from <see cref="EntityCollectionView{TEntity, TView}"/> and specializes it for <see cref="Actor"/>.
    /// </remarks>
    public sealed class ActorCollectionView : EntityCollectionView<IActor, ActorView>
    {
    }
}
