using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;

namespace Atomic.Entities
{
    internal static class EntityCollectionViewGenerator
    {
        public static void GenerateFile(
            string entityType,
            string interfaceType,
            string ns,
            string[] imports,
            string directory
        )
        {
            if (string.IsNullOrWhiteSpace(entityType))
            {
                EditorUtility.DisplayDialog("Error", "Entity Type cannot be empty.", "OK");
                return;
            }

            Directory.CreateDirectory(directory);
            string filePath = Path.Combine(directory, $"{entityType}CollectionView.cs");
            string content = GenerateContent(entityType, interfaceType, ns, imports);

            File.WriteAllText(filePath, content, Encoding.UTF8);
            AssetDatabase.Refresh();
        }

        private static string GenerateContent(string entityType, string interfaceType, string ns, string[] imports)
        {
            var sb = new StringBuilder();

            // --- Imports ---
            sb.AppendLine("using Atomic.Entities;");
            if (imports is { Length: > 0 })
            {
                foreach (string import in imports.Where(i => !string.IsNullOrWhiteSpace(i)))
                {
                    string clean = import.Trim();
                    sb.AppendLine(clean.StartsWith("using") ? clean : $"using {clean};");
                }
            }

            sb.AppendLine();
            sb.AppendLine("/**");
            sb.AppendLine(" * Created by Entity Domain Generator.");
            sb.AppendLine(" */");
            sb.AppendLine();

            // --- Namespace + CollectionView ---
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");

            // --- XML Docs ---
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// A collection view responsible for displaying and managing multiple <see cref=\"{entityType}View\"/> instances bound to <see cref=\"{interfaceType}\"/> entities.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    /// <remarks>");
            sb.AppendLine("    /// This class is automatically generated by <b>Entity Domain Generator</b>.");
            sb.AppendLine($"    /// It inherits from <see cref=\"EntityCollectionView{{TEntity, TView}}\"/> and specializes it for <see cref=\"{entityType}\"/>.");
            sb.AppendLine("    /// </remarks>");

            sb.AppendLine($"    public sealed class {entityType}CollectionView : EntityCollectionView<{interfaceType}, {entityType}View>");
            sb.AppendLine("    {");
            sb.AppendLine("    }");

            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
